server:
  port: 8083

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poa_academico?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: toor
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      write-dates-as-timestamps: true

security:
  header:
    prefix: "Bearer "
  jwt:
    secret: "crescer-2018-1-java-jwt"
    expiration: 86400000 # 1 dia em milisegundos
  public:
    path: "/public/**"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace## YAML Template.
---
